### ISSUE TITLE
mimick_vendor uses ament exports unexpectedly.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/mimick_vendor#25]
I think that mimick_vendor's [use of ament_export_](https://github.com/ros2/mimick_vendor/blob/76e51eedab0359ed56dc1099ed763db97f4275b7/CMakeLists.txt#L87-L89) functions is contrary to the preferred workflow for vendor packages but before opening PRs to address it (or alternatively to add a missing exported dependency on ament_cmake) I wanted to check if there is a specific rationale for doing so or if I am out-of-date on the preferred workflow for vendor packages.

Here's a thesis: vendor packages should be written in such a way, that when a vendor package is deprecated and removed the changes for packages consuming the vendored library should be exactly
1. Changing the dependency keys in `package.xml` from the vendor package to the rosdep key for the previously vendored project.
2. Removing `find_package(VENDORED_PROJECT_vendor ...)` from CMakeLists.txt.

Implicit in that thesis is that packages depending on vendored projects _must_ still `find_package(VENDORED_PROJECT ...)` explicitly once the vendor package has been found.

The advantage of that workflow is that removing a retired vendor package is a very rote action and can be done hopefully without further modification or reorganization of build scripts.

If there's agreement with that thesis I think that mimick_vendor's exports should be removed and the projects using mimick_vendor will need to be updated to `find_package(Mimick ...)` directly after `find_package(mimick_vendor ...)`. Without those exports, mimick_vendor does not actually do anything at build configuration time and so in theory find_package'ing the vendor package could be omitted but vendor packages may also supply CMake hooks or find modules for vendored projects so I think leaving it in is a best practice. Especially for non-ROS packages that lack a `package.xml` and rely on heuristic scanning of CMakeLists.txt for colcon dependency interaction.

If there is a preference for maintaining the current workflow, I think mimick_vendor needs to be updated to export its dependency on ament_cmake as these exports don't work without those cmake modules available at build configuration time.

**Comment by nuclearsandwich** [comment]
I should also mention that I stumbled down this path not because of any problems with mimick_vendor but due to problems with another vendor package which used it as a template.

**Comment by gbiggs** [comment]
I think your thesis makes sense. The ultimate goal of all `vendor` packages should be as a filler until a system version becomes available, and when that happens the minimal workflow required is best.

**Comment by nuclearsandwich** [comment]
> The ultimate goal of all `vendor` packages should be as a filler until a system version becomes available, and when that happens the minimal workflow required is best.

Yeah, I think eliminating all vendor packages through upstreaming is an asymptotic goal but as a release engineer I will quixotically pursue the goal of zero vendor packages.

@gbiggs are you a current maintainer of this vendor package? If so can I take the above as agreement that I should open PRs removing the exported dependency and patching downstream software to find_package mimick directly?

**Comment by gbiggs** [comment]
Turns out, I am! So feel free to make some PRs.

**Comment by mjcarroll** [comment]
I believe this is no longer relevant since switching to `ament_cmake_vendor_package`.  Feel free to re-open if this is incorrect.
