### ISSUE TITLE
mimick_vendor failed to compile

### ISSUE THREAD

**Issue by Jxfeii** [ros2/mimick_vendor#30]
**An error occurred while executing the command “colcon build --merge-install”  on windows**

-------------------
Summary: 106 packages finished [57.2s]

  1 package failed: mimick_vendor

  6 packages aborted: console_bridge_vendor qt_gui resource_retriever rosidl_cmake rosidl_runtime_cpp test_launch_testing

  13 packages had stderr output: cyclonedds fastcdr libcurl_vendor orocos_kdl osrf_testing_tools_cpp rviz_assimp_vendor rviz_ogre_vendor shared_queues_vendor test_osrf_testing_tools_cpp tracetools_read tracetools_trace yaml_cpp_vendor zstd_vendor

  198 packages not processed

WNDPROC return value cannot be converted to LRESULT

TypeError: WPARAM is simple, so must be an int object (got NoneType)

-------------------
**CMakeError.log info:**

CMakeCCompilerABI.c

cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f4c35.dir\Debug\\" /Fd"cmTC_f4c35.dir\Debug\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.25\Modules\CMakeCCompilerABI.c"

D:\VisualStudioIDE\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003: 指定的任务可执行文件“CL.exe”未能运行。System.IO.DirectoryNotFoundException: 未能找到路径“E:\foxy\build\mimick_vendor\mimick-f171450b5ebaa3d2538c762a059dfc6ab7a01039-prefix\src\mimick-f171450b5ebaa3d2538c762a059dfc6ab7a01039-build\CMakeFiles\CMakeScratch\TryCompile-s5cg0o\cmTC_f4c35.dir\Debug\cmTC_f4c35.tlog”的一部分。 [E:\foxy\build\mimick_vendor\mimick-f171450b5ebaa3d2538c762a059dfc6ab7a01039-prefix\src\mimick-f171450b5ebaa3d2538c762a059dfc6ab7a01039-build\CMakeFiles\CMakeScratch\TryCompile-s5cg0o\cmTC_f4c35.vcxproj]

**Comment by AdrienGenilec** [comment]
Same for me while trying to build ros2 humble from source on Windows 10, rviz2 was crashing with installation from binairies so I thought if I build it from source it may works...

Below is attached console output and all log files from latest build:
[latest_build.zip](https://github.com/ros2/mimick_vendor/files/11151549/latest_build.zip)
[Console output.txt](https://github.com/ros2/mimick_vendor/files/11151616/Console.output.txt)

**Comment by mjcarroll** [comment]
This should be resolved now: https://github.com/ros2/Mimick/pull/25

**Comment by Mark-Firestorm** [comment]
> This should be resolved now: [ros2/Mimick#25](https://github.com/ros2/Mimick/pull/25)

I just ran into this same error, I resolved it by switching the mimick_vendor branch from humble to rolling, thankfully this is a shim package and doesn't change too much.  I think some changes need to be brought to the humble branch to resolve building successfully (I followed the ROS Humble Windows Source Build instructions directly, this was the only package that failed on me.)
