### ISSUE TITLE
compilation error due to -Werror

### ISSUE THREAD

**Issue by goekce** [ros2/mimick_vendor#9]
I am on Archlinux using GCC 10.2 and get the following error while building ROS:
```
--- stderr: mimick_vendor
In file included from /usr/include/errno.h:25,
                 from /opt/ros/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/include/mimick/mock.h:27,
                 from /opt/ros/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/include/mimick/mimick.h:401,
                 from /opt/ros/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/sample/strdup/test.c:1:
/usr/include/features.h:397:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
In file included from /usr/include/errno.h:25,
                 from /opt/ros/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/include/mimick/mock.h:27,
                 from /opt/ros/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/include/mimick/mimick.h:401,
                 from /opt/ros/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/test/test.c:1:
/usr/include/features.h:397:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
```
Is it related to the upstream library `ros2/mimick` or it is a cmake-related configuration error? If related to mimick, I can happily post it there.

**Comment by goekce** [comment]
Workaround:
```
sed -i 's/-Werror//' $YOUR_BUILD_DIR/mimick_vendor/mimick-ext-prefix/src/mimick-ext/{test,sample}/CMakeLists.txt
```

**Comment by goekce** [comment]
Opened issue upstream: https://github.com/Snaipe/Mimick/issues/16

**Comment by goekce** [comment]
I noticed that this error does not happen when Mimick is built standalone (clone Mimick & cmake & make).

**Comment by hidmic** [comment]
@goekce I'm unable to reproduce using `gcc` 10.2 on ArchLinux. Could you provide us with a bit more information? Which version of ROS are you building? How? Which OS version and setup? A repro would be ideal.

**Comment by goekce** [comment]
I recompiled foxy again, and I get no errors anymore... Probably it was fixed.

And I should have given more details about the steps, I will pay attention to that next time.

thank you @hidmic and @clalancette !

**Comment by goekce** [comment]
@hidmic I found out the source of this error. It only happens when I use `makepkg`. I compile whole ROS using makepkg to create a ros-foxy package. `makepkg` sets the environment variable `CPPFLAGS="-D_FORTIFY_SOURCE=2"` probably [due to security reasons](https://idea.popcount.org/2013-08-15-fortify_source/). But for this option optimizations must be turned on and probably the tests in `mimick` have optimizations turned off, so a warning is thrown. This again leads to an error because the tests are compiled with `-Werror`.

In my `PKGBUILD` `build()` function I have now unset `CPPFLAGS`, and foxy compiles fine using `makepkg`.

**Comment by hidmic** [comment]
>  probably the tests in mimick have optimizations turned off

And that's very much on purpose. With optimization comes function inlining, and thus `.got` and `.got.plt` poisoning becomes unreliable.
